remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter

title: Thailand Essential Apps
description: Curated must-have apps for travelers, expats, and digital nomads in Thailand.
just_the_docs:
  color_scheme: light