remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter

title: Thailand Essential Apps
description: Curated must-have apps for travelers, expats, and digital nomads in Thailand.

# Just the Docs theme configuration
just_the_docs:
  color_scheme: light
  search_enabled: true
  search:
    # Split pages into sections that can be searched individually
    # with a maximum of 6,000 words per section
    heading_level: 2
    previews: 3
    previews_before: 2
    previews_after: 1
    tokenizer_separator: /[\s/]+/
  aux_links:
    "GitHub":
      - "//github.com/jdelaire/thailand-essentials-apps"

# Navigation structure
navigation:
  - title: Home
    url: /
  - title: Transport
    url: /transport
  - title: Money
    url: /money
  - title: Food
    url: /food
  - title: Housing
    url: /housing
  - title: Social
    url: /social
  - title: Shopping
    url: /shopping